### PR TITLE
A proposed change to the way MessageHandler delegates are created.

### PR DESCRIPTION
**Pull request by Eleocraft**
so I started to setup a project with a playerhostet server, and there is one little thing I think you could change to improve the quality of life when doing this kinds of projects. In order to keep my code clean in many cases I want the same behaviour when receiving a message as a server and as a client. However, since the MessageHandler Delegates are not the same for clients and servers, I will always need two static functions. One for the server (with ushort fromClientId) and one for the client (Without the ushort). It is just a small thing, but I think it would be simpler if the ushort weren't necessary but optional on servers.

With these changes, when the server script finds a clientMessageHandler or vice versa, It just gets converted using a Generic Action<> and a lambda expression:

serverMessageHandler = (MessageHandler)((clientId, message) => clientMessageHandler(message));

(Also for whatever reason the serverMessageHandler variable in the Server.cs script was named clientMessageHandler, I also changed that (just to prevent confusion))

### CODE REVIEW

**Comment by tom-weiland** [comment]
> However, since the MessageHandler Delegates are not the same for clients and servers, I will always need two static functions

This is intentional, because 99% of the time clients and servers aren't receiving the same messages containing the same data, and even in the unusual circumstance where that *is* the case, a client rarely needs to execute the exact same logic as the server does.

I'll be honest, I have yet to encounter a scenario in my own projects where it would be possible (let alone where it *makes sense*) for client and server to share the same message handler method. If you could elaborate on what your project setup/architecture is and what you're trying to achieve, maybe there's a better/existing way to do it, or maybe I'll see the need for this sort of feature.

> With these changes, when the server script finds a clientMessageHandler or vice versa, It just gets converted using a Generic Action<> and a lambda expression:
>
> serverMessageHandler = (MessageHandler)((clientId, message) => clientMessageHandler(message));

The thing is that (as I mentioned above) the separation between message handler signatures exists *on purpose*. Making them interchangeable could cause major problems in projects where the client and server code are running in the same application.

If I've set up a message handler for input packets that clients send to my server, I don't want the clients to be using that same method to handle messages with the same ID. If you manage to convince me that making message handlers interchangeable like this (which I'm still skeptical about) is necessary, it would definitely need to be implemented differently than it currently is in this pull request.

> (Also for whatever reason the serverMessageHandler variable in the Server.cs script was named clientMessageHandler, I also changed that (just to prevent confusion))

Good catch, I probably forgot to change it when I copied the `CreateMessageHandlersDictionary` method to the `Server` class.

**Comment by Eleocraft** [comment]
Well I am working on a player hosted game that is build in a way that it can't be competitive. There should be one host, and than his friends can join as clients. Like for example in raft. Since this game will only make sense to play with friends I don't care about client manipulation or anything. So I figured it would be way simpler to keep the logic completely client-based, and only send the results back and forth. This also has performance advantages because it means that the hosting player won't need to calculate all the actions from all the players. That means that the server basically just serves as a data-HUB: every time the server receives a message from a client, the server just sends the data to every other client, and when the server wants to send some data it just does a SendToAll. Most of the time I basically treat the server as a client with the ID 0. This works for most standart actions (For example Player movement already works fine in my project) but obviously not every time:

> The thing is that (as I mentioned above) the separation between message handler signatures exists on purpose. Making them 
interchangeable could cause major problems in projects where the client and server code are running in the same application.

Well the thing is that (correct me if im wrong but) I can't think of a scenario where the client and the Server are running _At the same time_ (except maybe in some kind of Peer-to-Peer thing, but that would be overly complicated). At least in my Project if i need to use server or client specific actions I can just check if the current instance of my game is hosting or a client. But I agree that this kind of custom logic might not be that convenient for most people so I thaught of a better way: maybe it would be possible to add another boolean property to the messageHandlerAttribute, like for example "clientServerIndependent" that could be set to false by default, but if its set to true the message Handler works for Server _and_ Client. This would probably be really easy to implement, I will try that out later.

>  it would definitely need to be implemented differently than it currently is in this pull request.

Is this what you meant or did I miss anything?

> maybe there's a better/existing way to do it

Very possible, because I am quite new to Riptide. If there is a better way I would really like to hear about that, but up now my way seems to work fine.

**Comment by tom-weiland** [comment]
> I can't think of a scenario where the client and the Server are running *At the same time*

Any time you have a client hosting a game.
Maybe you've set it up differently, but in my opinion the cleanest way to make a client act as a host is to run a Server instance and connect to it locally with a Client instance (like in the [Steam transport](https://github.com/tom-weiland/RiptideSteamTransport)'s demo). That way the local player can be treated the same as other players and reuse the same code.

> if i need to use server or client specific actions

Isn't pretty much everything a server- or client-specific action? For example, a client receiving a position message would want to move the player, but if the server receives a position message it needs to send that message on to everyone else, so it's different logic...

> Is this what you meant or did I miss anything?

Yeah that might work 🤔 but I'm still not sure that something like this is necessary...

**Comment by Eleocraft** [comment]
> Any time you have a client hosting a game.
Maybe you've set it up differently, but in my opinion the cleanest way to make a client act as a host is to run a Server instance and connect to it locally with a Client instance (like in the Steam transport's demo). That way the local player can be treated the same as other players and reuse the same code.

Yea that would be a way to handle it... But wouldn't that use up more performance than just using a server _as_ a client? I really don't know if that would make a difference. Currently my Multiplayer implementation works in a way that the server instance gets treated as a client instance even if it isn't one, but maybe it would be easyer to create a client _and_ a server at the hosting position. Honestly I never thaught of having a server seperate from a client in the hosting instance.

> Isn't pretty much everything a server- or client-specific action? For example, a client receiving a position message would want to move the player, but if the server receives a position message it needs to send that message on to everyone else, so it's different logic...

Currently I am doing this in the MessageReceived method, and only exclude certain messages.

**Comment by tom-weiland** [comment]
> But wouldn't that use up more performance than just using a server as a client?

Barely, and whatever small amount of performance you're sacrificing is well worth the amount of extra code you're saving yourself from writing.

> Currently my Multiplayer implementation works in a way that the server instance gets treated as a client instance even if it isn't one

Doesn't that require a lot of branching in your logic? If server, do this, otherwise do that. If this is the local player do it this way, otherwise do it that way. Etc.

> However I end up doing it I think being able to decide if server messages should be handled seperately or not is still a good addition to have.

Yeah maybe, although I could see it being one of those options that almost no one ever uses :P

**Comment by Eleocraft** [comment]
> Doesn't that require a lot of branching in your logic? If server, do this, otherwise do that. If this is the local player do it this way, otherwise do it that way.

No not really, basically I have a serverHandler and a clientHandler class both with the INetworkingHandler interface. They than both have functions like Send or GetId that obviously work differently on a client and on a server. Up now that never got complicated. The thing is that sometimes you _want_ a host behaving differently than the other players, like for example when saving the game. So I am not sure I am saving myself a lot of codewriting there. Could be wrong though.

> although I could see it being one of those options that almost no one ever uses

I would use it :P

**Comment by tom-weiland** [comment]
> The thing is that sometimes you want a host behaving differently than the other players

Well you would do that from the "server-side". If you maintain that separation of logic even when client and server are in the same project/application, saving game data would only be done by the one acting as the server, requiring no more code than you'd have to write with your current setup.

> Also it's kinda off topic but is there an integrated way to convert URLs to IPs?

Integrated into Riptide? No.

**Comment by tom-weiland** [comment]
So one major issue with merging this is that it would cause errors in situations where you have a client message handler method for messages with ID 1, and a server message handler method for messages with ID 1, with both of their `clientServerIndependent` parameters set to true. Any Server or Client instance starting in that context would try to add both of these methods to its handlers dictionary using the same ID, which will obviously throw an exception.

I suppose Riptide could prioritize the method whose signature matches that of whatever (server or client) is adding it to its dictionary and spit out some kind of warning, but making that warning helpful to the user is more difficult than I initially thought.

```
serverMessageHandler = (MessageHandler)((clientId, message) => clientMessageHandler(message));
```
This line makes `serverMessageHandler` an anonymous method, meaning that `serverMessageHandler.GetMethodInfo().Name` will no longer return the actual handler method's name. Similarly, retrieving the original method's *real* signature doesn't work, which prevents determining whether or not the new/second method with the same ID should be prioritized over the one already in the dictionary.

I'm not sure if it's possible to "unwrap" an anonymous method in a way that would allow retrieving the "internal" method's name/information, but this really feels like it's getting overly complicated for something that I still don't think is necessary.

Could you provide some code examples for where you actually need this, because I'm really struggling to see a scenario where needing this kind of functionality *isn't* the result of some—for lack of a better word—suboptimal logic/architecture choices...

**Comment by Eleocraft** [comment]
> you have a client message handler method for messages with ID 1, and a server message handler method for messages with ID 1, with both of their clientServerIndependent parameters set to true.

This would definitly be a user error because it makes no sense. setting clientServerIndependent to true only makes sense when you want a method for the client _and_ the server. so in my opinion if the user tries to add two clientServerIndependent functions with the same Id you could just throw an error. There is no need for a warning or prioritizing anything. throw an exeption when the client/server script tryies to add a second clientServerIndependent function with an ID that is already taken.

> Could you provide some code examples for where you actually need this, because I'm really struggling to see a scenario where needing this kind of functionality isn't the result of some—for lack of a better word—suboptimal logic/architecture choices...

So since I am still very early in the development of my Multiplayer part I thaugth that it wouldn't hurt to try it your way.

> Maybe you've set it up differently, but in my opinion the cleanest way to make a client act as a host is to run a Server instance and connect to it locally with a Client instance (like in the Steam transport's demo). That way the local player can be treated the same as other players and reuse the same code.

This didn't take long to implement, but the thing is, that my ServerManager code now looks like this:

    [MessageHandler((ushort)MessageId.commands)]
    private static void ReceiveCommand(ushort Id, Message message) 
    {
        Server.SendToAll(message, Id);
    }

    [MessageHandler((ushort)MessageId.playerData)]
    private static void ReceivePlayerData(ushort Id, Message message)
    {
        Server.SendToAll(message, Id);
    }

    [MessageHandler((ushort)MessageId.playerAnimData)]
    private static void ReceiveAnimData(ushort Id, Message message)
    { 
        Server.SendToAll(message, Id);
    }

I cannot think of a scenario where that would be more convenient than just have the server act as a client.

**Comment by tom-weiland** [comment]
> This would definitly be a user error because it makes no sense.

Agreed, but I despise vague error messages, and making this error as descriptive as I'd ideally like it to be (considering it's caused by *very* specific circumstances) isn't going to work as far as I can tell.

> This didn't take long to implement, but the thing is, that my ServerManager code now looks like this:

Yeah that's definitely not ideal. I actually just had someone else also mention they had a lot of messages that the server just passes on to all other clients and if there might be a way to automate that.

What I'm considering is adding something like a 3rd message send mode, which would cause the server to internally pass on messages with that send mode to other clients. Do you think that would adequately address your use case(s) for interchangeable message handlers?

**Comment by Eleocraft** [comment]
> What I'm considering is adding something like a 3rd message send mode, which would cause the server to internally pass on messages with that send mode to other clients. Do you think that would adequately address your use case(s) for interchangeable message handlers

Yes this sounds like a good addition to riptide. I still think that my way is also an elegant way to handle the problem, but in the end it won't make a big difference for my project so I'm fine with doing it the "client+server on host pc" way.

> I despise vague error message

Just for the record: 
What I meant is to throw the error when the method gets found so _before_ it gets wrapped in a lamda. You could easily get the informations you want by using GetMethodInfo().

**Comment by tom-weiland** [comment]
> What I meant is to throw the error when the delegate is created so before it gets wrapped into a lamda.

Hmm but at that point you don't necessarily know whether there is another handler method for the same ID (unless you loop through all the rest of the methods and check all of them), and if there isn't, that's intended behaviour so you obviously don't want to throw that exception.

> Yes this sounds like a good addition to riptide. I still think that my idea is also an elegant way to handle the problem, but in the end it won't make a big difference for my project so I'm fine with doing it the "client+server on host pc" way.

Alright, in that case I'll probably close this once I've added that.

**Comment by Eleocraft** [comment]
> Hmm but at that point you don't necessarily know whether there is another handler method for the same ID (unless you loop through all the rest of the methods and check all of them), and if there isn't, that's intended behaviour so you obviously don't want to throw that exception

Yes but you don't need to throw the exception when the message Id is found for the first time, but when it is found a second time. You could just temporarily store the method info and then use it if the dictionary already contains the I'd, exactly like it is now for methods of the same delegate.

> Alright, in that case I'll probably close this once I've added that.

Ok

**Comment by tom-weiland** [comment]
So as of 2a09f6ebdf72e3f12075abb4ab56ee28a7e55b8f, you can set your Server's `AllowAutoMessageRelay` property to true, and then any messages you create (with the `shouldAutoRelay` parameter set to true) and send through a Client instance will be automatically forwarded to all other clients when the server receives them.

This won't be in the Unity package until v1.2.0 is released, so in the meantime you'll need to build the solution yourself and use the dll.

**Pull request closed without merging**
