### PR TITLE
Add MonoGame Demo

### PR DESCRIPTION
**Pull request by IrishBruse**
A super simple MonoGame demo that has white squares moving around on screen

https://user-images.githubusercontent.com/14964651/148620608-4f36d945-a313-4898-9291-8f97a4f3d13a.mp4

### CODE REVIEW

**Comment by tom-weiland** [comment]
So I have no experience with MonoGame, and I've got no idea how widely used it is—do you think it's actually worth including a demo for it? 🤔

**Comment by IrishBruse** [comment]
Its fine to not merge it in just to have it here if people come looking.

**Comment by ERmilburn02** [comment]
I feel like it would be nice to have a demo that isn't Unity but still has graphics. Monogame will keep it simple, whilst still providing a good demo to show off Riptide.

**Comment by tom-weiland** [comment]
> Its fine to not merge it in just to have it here if people come looking.

Well I don't really want to leave it open, and closing it would make it harder to find, so I suppose I may as well merge it. Regarding the copyright though, you put my copyright header in all the files with my name—but that seems weird considering you @IrishBruse wrote the code... 🤔

**Comment by IrishBruse** [comment]
Oh oops I copy and pasted it with out really thinking I can change it if you want

**Pull request closed without merging**
