### PR TITLE
fixed max message size problem

### PR DESCRIPTION
**Pull request by Mortal-Dev**
I've been having issues with meeting the max message size when stress-testing a snapshot-based networking solution that utilizes RiptideNetworking, the proposals I added would add the ability for users to change the max message size without making any breaking changes (people already using RitpideNetworking can just update, and don't have to change any of their code)

### CODE REVIEW

**Comment by tom-weiland** [comment]
I'm not really sure how I feel about setting the `MaxMessageSize` in the `Connect`/`Start` methods as it's a static (aka project-wide) property. I think I'd prefer some kind of config file, which is something I've been considering setting up for a while.

Also the way you've set it up, I'm pretty sure that `Connect`ing to a server twice without restarting the application would cause that exception in the message size's setter to be thrown (since you're setting it every time a server starts/client connects, even if no value is passed in for that parameter).

On more of a "housekeeping" note, why has the `RiptideNetworking.sln` file been moved to the UnityPackage folder, and why are there committed changes to files in the .vs folder? That whole thing is on the gitignore if I'm not mistaken...

**Comment by Mortal-Dev** [comment]
Valid points, I was having problems in visual studio, I can remedy these and have the MaxMeasageSize probably set in the Client or Server constructor, and figure put the if check

**Comment by tom-weiland** [comment]
I don't think the constructors are the right place either, as it's not uncommon to run a server and client instance in the same project (or potentially multiple server/client instances). Considering the max message size is a universal property, I think it belongs in a config file, and really nowhere else.

**Comment by Mortal-Dev** [comment]
while this is a personal thing, I believe that the MaxMessageSize shouldn't be in a config file, as it would add an unnecessary layer of abstraction, and it would be much simpler to have the user define it in the connect/start methods (I was wrong about setting it in the constructor).  I wouldn't recommend creating a config file unless there's a decently large amount of options that would look cluttered in code.  (this ain't my project tho, so do what u want)

**Comment by tom-weiland** [comment]
I mean the alternative would be to make the `MaxMessageSize` a static property (basically like you did), but that's somewhat dangerous because the max size shouldn't be changing after instances of the `Message` class have been created as that can quickly lead to problems.

I have an idea on how to address that, and considering this PR now shows (what appears to be) every line in every single file as changed, it's probably best if I just make the change myself :P

**Comment by Mortal-Dev** [comment]
wait what, how did that happen???  All the lines are the same!  Anyways, if you don't wanna merge it, that's cool, I'll just use this branch for personal stuff until you implement something similar.  I can think of ways to check if there's message instances active when the MaxMessageSize is set, but you got this 👍

**Comment by tom-weiland** [comment]
> All the lines are the same!

Yeah I have no idea what happened there. They're all the same but they all show as changed 🤔

> until you implement something similar

I'll probably do it this weekend, although it won't be part of an "official" version for a while because there's other things I want to add/fix before the next update, so you'll have to rebuild the dlls yourself if you want it before then.

**Comment by Mortal-Dev** [comment]
anyways, I added a fix for checking if a message instance has been created (thanks for reminding me lol)

**Comment by tom-weiland** [comment]
Reopening because I should probably close it along with the actual commit 😅

**Comment by karisigurd4** [comment]
Keep in mind. External configuration files tend to bring a bit more maintenance cost than you initially bargained for. Maybe throwing a runtime exception if the value is changed inappropriately would be good enough to quickly let any developer know they're doing something bad.

**Comment by Mortal-Dev** [comment]
> Maybe throwing a runtime exception if the value is changed inappropriately would be good enough to quickly let any developer know they're doing something bad.

Implemented this

**Comment by tom-weiland** [comment]
You can now set `Message.MaxPayloadSize` to a higher value, as long as you do it while no servers or clients are running. The default is still 1250.

**Pull request closed without merging**
